# Generated by Django 2.2.13 on 2020-06-22 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('era_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AddField(
            model_name='tag',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='era_blog.Category', verbose_name='文章分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(upload_to='article/%Y/%m/', verbose_name='文章封面'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='era_blog.Tag', verbose_name='文章标签'),
        ),
    ]
