# Generated by Django 3.2.25 on 2026-05-09 07:33

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('era_blog', '0002_auto_20200622_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=martor.models.MartorField(verbose_name='文章内容'),
        ),
    ]
