# Generated by Django 3.2.25 on 2026-05-20 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('era_blog', '0003_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='era_blog.category', verbose_name='父分类'),
        ),
    ]
